# Generated by Django 5.0.6 on 2024-05-31 14:48

import django.db.models.deletion
import pong.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_won_parties', models.IntegerField(default=0)),
                ('nbr_lose_parties', models.IntegerField(default=0)),
                ('total_time_played', models.DurationField(default=0)),
                ('nbr_won_tournaments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pseudo', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.BinaryField(validators=[pong.models.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(through='pong.Friendship', to='pong.user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='pong_user_set', related_query_name='pong_user', to='auth.group')),
                ('statistic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_statistic', to='pong.statistic')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='pong_user_set', related_query_name='pong_user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_tournaments1', to='pong.user')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_tournaments2', to='pong.user')),
                ('participant3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_tournaments3', to='pong.user')),
                ('participant4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_tournaments4', to='pong.user')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_tournaments', to='pong.user')),
            ],
        ),
        migrations.AddField(
            model_name='statistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_user', to='pong.user'),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_time', models.DurationField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='pong.tournament')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_parties', to='pong.user')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_parties', to='pong.user')),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='pong.user'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_of', to='pong.user'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('person1', 'person2')},
        ),
    ]
