# Generated by Django 5.0.6 on 2024-07-17 12:06

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0022_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
